import {collectGlobalPro} from './globalpro';
import {AppError,config,db} from './server';
import {parseEA,type TeamId} from './domain';
export async function ea(path:string,params:Record<string,string>){const url=new URL(`https://proclubs.ea.com/api/fc/${path}`);for(const [k,v]of Object.entries(params))url.searchParams.set(k,v);const r=await fetch(url,{headers:{Accept:'application/json, text/plain, */*','Accept-Language':'pt-BR,pt;q=0.9,en;q=0.8',Origin:'https://www.ea.com',Referer:'https://www.ea.com/','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36'},signal:AbortSignal.timeout(20000)});if(!r.ok)throw new AppError(`EA indisponível (HTTP ${r.status}). Os dados já salvos foram preservados.`,502);const text=await r.text();if(text.length>8000000)throw new AppError('Resposta da EA excedeu o limite.',502);try{return JSON.parse(text)}catch{throw new AppError('A EA não retornou dados válidos.',502)}}
export async function sync(team:TeamId){const c=await config(team);let hasEA=/^\d+$/.test(c.clubId??'');const now=Date.now();const lock=await db().prepare('INSERT INTO sync_locks (team, until) VALUES (?, ?) ON CONFLICT(team) DO UPDATE SET until=excluded.until WHERE sync_locks.until < ? RETURNING team').bind(team,now+240000,now).first();if(!lock)throw new AppError('Coleta recente ou em andamento. Aguarde alguns minutos.',429);
 const at=new Date().toISOString();let count=0;const errors:string[]=[];let succeeded=0;
 try{const gp=await collectGlobalPro(team);count+=gp.count;succeeded++}catch(e){errors.push(e instanceof Error?e.message:'Falha GlobalPro')}
 const backoff=await db().prepare("SELECT data FROM snapshots WHERE team=? AND source='ea-backoff'").bind(team).first<any>();if(hasEA&&backoff&&JSON.parse(backoff.data).until>Date.now()){hasEA=false;errors.push('EA temporariamente indisponível. Nova tentativa automática em até 5 minutos.')}
 const sources=hasEA?[['clubs/matches',{matchType:'leagueMatch',maxResultCount:'20'}],['clubs/matches',{matchType:'friendlyMatch',maxResultCount:'20'}],['clubs/matches',{matchType:'playoffMatch',maxResultCount:'20'}],['clubs/info',{}],['members/stats',{}],['members/career/stats',{}],['clubs/overallStats',{}],['clubs/seasonalStats',{}]] as const:[];
 for(const [path,extra] of sources){try{const raw=await ea(path,{platform:c.platform,clubIds:c.clubId,clubId:c.clubId,...extra});if(path==='clubs/matches'){if(!Array.isArray(raw))throw new Error('Formato inesperado');const rows=raw.map(m=>parseEA(m,c.clubId,extra.matchType!)).filter(Boolean);for(let i=0;i<rows.length;i+=15){await db().batch(rows.slice(i,i+15).map(m=>db().prepare('INSERT INTO matches (team, id, data, playedAt, importedAt) VALUES (?, ?, ?, ?, ?) ON CONFLICT(team,id) DO UPDATE SET data=excluded.data, playedAt=excluded.playedAt, importedAt=excluded.importedAt').bind(team,`${c.edition}:${c.platform}:${m!.id}`,JSON.stringify({...m,id:`${c.edition}:${c.platform}:${m!.id}`}),m!.playedAt,at)))}count+=rows.length}else{await db().prepare('INSERT INTO snapshots (team, source, data, at) VALUES (?, ?, ?, ?) ON CONFLICT(team,source) DO UPDATE SET data=excluded.data, at=excluded.at').bind(team,path,JSON.stringify(raw),at).run()}await db().prepare("DELETE FROM snapshots WHERE team=? AND source='ea-backoff'").bind(team).run();succeeded++}catch(e){errors.push(`${path}${'matchType' in extra?' · '+extra.matchType:''}: ${e instanceof Error?e.message:'falha'}`);if(e instanceof Error&&e.message.includes('HTTP 403')){await db().prepare("INSERT INTO snapshots (team,source,data,at) VALUES (?,'ea-backoff',?,?) ON CONFLICT(team,source) DO UPDATE SET data=excluded.data,at=excluded.at").bind(team,JSON.stringify({until:Date.now()+300000,reason:'HTTP 403'}),at).run();break}}}
 const status=succeeded&&!errors.length?'success':succeeded?'partial':'error';await db().prepare('INSERT INTO sync_runs (id, team, at, status, detail) VALUES (?, ?, ?, ?, ?)').bind(crypto.randomUUID(),team,at,status,JSON.stringify({count,errors})).run();return {status,count,errors,at};}
